consumer_key: 'TTIpUb3rFRk4u3PNc5QHQ'
consumer_secret: 'J5TEKpRpbXy2UyuFNymPWAuHJhEY9eDpNWwI4VVBmY'
callback_url: 'http://www.exerciseoneone.com/access'
login: 'teamftf'
apiKey: 'R_eec33b9a7bceced0f7350374f599a8ac'
